Feature/tasks
GabrielPradoC/projeto-helpper pull request #3
Opened 2021-12-08 16:34 UTC by GabrielPradoC

2021-12-08 16:35 UTC, GabrielPradoC commented
![](https://github.trello.services/images/mini-trello-icon.png) [04 - Cadastro de atividades](https://trello.com/c/PXOHSa3j/339-04-cadastro-de-atividades)

2021-12-20 10:37 UTC, elian-medeiros requested changes

2021-12-20 10:37 UTC, elian-medeiros commented on src/modules/users/v1/controllers/TaskController.ts
> +    @PublicRoute()
Esse decorator está efetivamente em uso? Acredito que não está refletindo em nada e essas rotas não são publicas

2021-12-20 10:45 UTC, GabrielPradoC commented on src/modules/users/v1/controllers/TaskController.ts
> +    @PublicRoute()
Código corrigido.

2021-12-20 10:48 UTC, elian-medeiros approved these changes

2021-12-20 11:08 UTC, merged